---
- name: test file creation
  ansible.builtin.file:
    path: /home/ansible/test_ansible
    state: touch
    mode: 0775

- name: testing ansible shell module
  ansible.builtin.shell:
    cmd: |
      echo "user: $(whoami), date: $(date), hostname: $(hostname)" >> /home/ansible/test_ansible

- name: update apt cache with sudo
  # run task with sudo
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    update_cache: yes