---
- name: Create /opt/bingo directory for app
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: /opt/bingo
    state: directory
    mode: 0777

- name: Copy bingo exec file
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: app/bingo
    dest: /opt/bingo/bingo
    mode: 0777

- name: Copy bingo config
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: app/config.yaml
    dest: /opt/bingo/config.yaml
    mode: 0777

- name: Create bingo directory /opt/bongo/logs/a9385ac2b4/ for main.log
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: /opt/bongo/logs/a9385ac2b4
    state: directory
    mode: 0777

- name: Copy systemd.service config for bingo app
  become: yes
  become_method: sudo
  ansible.builtin.copy:
    src: app/bingo.service
    dest: /etc/systemd/system/bingo.service
    mode: 0755

- name: Start and enable bingo.service
  become: yes
  become_method: sudo
  ansible.builtin.systemd:
    enabled: true
    state: restarted
    daemon_reload: true
    name: bingo

- name: Setup a cronjob for /ping healthcheck
  become: yes
  become_method: sudo
  ansible.builtin.cron:
    name: "bingo healthcheck job"
    job: "if [[ $(curl -s -i http://localhost/ping | head -1 | awk -F' ' '{print $2}') == '500' ]]; then /bin/systemctl restart bingo; fi"
