student_email: glebgerlah@yadex.ru
postgres_cluster:
  hosts:
  - address: 51.250.13.100
    port: 5432
  user: postgres
  password: postgres
  db_name: postgres
  ssl_mode: disable
  use_closest_node: false
