student_email: glebgerlah@yadex.ru
postgres_cluster:
  hosts:
  - address: 10.5.0.23
    port: 5432
  user: postgres
  password: postgres
  db_name: postgres
  ssl_mode: disable
  use_closest_node: false
